@baseUrl = http://localhost:3000/api
###VERCEL
###@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 1. Összes felhasználó lekérése
GET {{baseUrl}}/users
Content-Type: application/json

### 2. Regisztráció tesztelése
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Kovács János2",
    "email": "janika@gmail.com",
    "password": "titkosjelszo123",
    "role": "PATIENT"
}

### 3. Felhasználó törlése (Az ID-t cseréld ki egy létezőre a listádból!)
DELETE {{baseUrl}}/users/6989aa07e68d621ab6b094b4
Content-Type: application/json