@baseUrl = http://localhost:3000/api
###VERCEL
###@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 1.1 Összes felhasználó lekérése
GET {{baseUrl}}/users
Content-Type: application/json

### 1.2 Összes orvos lekérése
GET {{baseUrl}}/users/doctors
Content-Type: application/json

### 1.3 Összes páciens lekérése
GET {{baseUrl}}/users/patients
Content-Type: application/json

### 2. Regisztráció 
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Kovács János",
    "email": "janos@gmail.com",
    "password": "titkosjelszo123",
    "phone": "+36301234567",
    "tajNumber": "123 456 789",
    "address": "9022 Győr, Városház tér 1.",
    "role": "PATIENT"
}

### 3. Bejelentkezés
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "janos@gmail.com",
    "password": "titkosjelszo123"
}
### 4. Profil lekérése
GET {{baseUrl}}/users/profile
Authorization: Bearery eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljMjZmNDcyNzgyMTdlNjY3NjgyNCIsImlhdCI6MTc3MDYzNTkwMSwiZXhwIjoxNzczMjI3OTAxfQ.Gq9OTDUsxEr4JSP9MGsnf3XzRsb9amPrsOZYYJd6sKE

### 5. Profil frissítése (Név és telefonszám módosítása)
PUT {{baseUrl}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljMjZmNDcyNzgyMTdlNjY3NjgyNCIsImlhdCI6MTc3MDYzNTkwMSwiZXhwIjoxNzczMjI3OTAxfQ.Gq9OTDUsxEr4JSP9MGsnf3XzRsb9amPrsOZYYJd6sKE
Content-Type: application/json

{
    "name": "Kovács János Úr",
    "phone": "+36709998877",
    "address": "1011 Budapest, Fő utca 1."
}
### 6. Felhasználó törlése 
DELETE {{baseUrl}}/users/6989c1c5d713db859db1cedf
Content-Type: application/json