@baseUrl = http://localhost:3000/api
###VERCEL
@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 1. Összes felhasználó lekérése
GET {{baseUrl}}/users
Content-Type: application/json

### 2. Bejelentkezés (Még nem működik, csak a teszt vázlata)
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "teszt@elek.hu",
    "password": "jelszo123"
}