@baseUrl = http://localhost:3000/api
###VERCEL
###@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 0. Admin login
# @name adminLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pwd"
}

### 0. Paciens login
# @name patientLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "janos@gmail.com",
    "password": "titkosjelszo123"
}

### 0. Orvos login
# @name doctorLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "doktorjani@gmail.com",
    "password": "pwd"
}

### 1.1 Összes időpont lekérése ADMIN ONLY
GET {{baseUrl}}/appointments
Authorization: Bearer {{adminLogin.response.body.token}}
Content-Type: application/json