@baseUrl = http://localhost:3000/api
###VERCEL
###@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 0. Admin login
# @name adminLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pwd"
}

### 0. Paciens login
# @name patientLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "szemethylevente2@gmail.com",
    "password": "doktorcigany2"
}

### 0. Orvos login
# @name doctorLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "szemethylevente3@gmail.com",
    "password": "doktorcigany2"
}

### 1.1 Összes rekord lekérése ADMIN ONLY
GET {{baseUrl}}/records
Authorization: Bearer {{adminLogin.response.body.token}}
Content-Type: application/json

### 1.2 Páciens kórtörténetének lekérése (ID alapján)
GET {{baseUrl}}/records/patient/698ed3805990de5da799ea52
Authorization: Bearer {{doctorLogin.response.body.token}}
Content-Type: application/json

### 1.3. SAJÁT IDŐPONTOK (Orvos látja a pácienseit)
GET {{baseUrl}}/appointments/my
Authorization: Bearer {{doctorLogin.response.body.token}}

### 1.4. SAJÁT KÓRTÖRTÉNET LEKÉRÉSE (Páciens a saját leleteit látja)
GET {{baseUrl}}/records/my
Authorization: Bearer {{patientLogin.response.body.token}}

### 2. Új rekord létrehozása (ORVOSKÉNT)
POST {{baseUrl}}/records
Authorization: Bearer {{doctorLogin.response.body.token}}
Content-Type: application/json

{
    "patient": "698ed3805990de5da799ea52",
    "description": "Végbélrák gyanúja, további vizsgálatok szükségesek.",
    "service_id": "698edacaeb2bfa2473c91159"
}


