@baseUrl = http://localhost:3000/api
###VERCEL
###@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 0. Admin login
# @name adminLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "pwd"
}

### 0. Paciens login
# @name patientLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "janos@gmail.com",
    "password": "titkosjelszo123"
}

### 0. Orvos login
# @name doctorLogin
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "doktorjani@gmail.com",
    "password": "pwd"
}
### 0. Orvos2 login
# @name doctorLogin2
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "doktorjani2@gmail.com",
    "password": "doktorcigany2"
}

### 1. Összes szolgáltatás lekérése (Public)
GET {{baseUrl}}/services
Content-Type: application/json

### 2.1 Új szolgáltatás létrehozása - Minden elvárt mezővel
# @name createService
POST {{baseUrl}}/services
Authorization: Bearer {{doctorLogin.response.body.token}}
Content-Type: application/json

{
    "doctor_id": "698a3e705cf74c640c1f4b1c",
    "topic": "Kardiológia",
    "description": "Rövid, 30 perces beavatkozás",
    "location": "102-es vizsgáló",
    "date": "2026-05-20T10:00:00.000Z",
    "price": "1 lélek"
}

### 2.2 Új szolgáltatás létrehozása - ADMIN (Bármelyik orvoshoz)
POST {{baseUrl}}/services
Authorization: Bearer {{adminLogin.response.body.token}}
Content-Type: application/json

{
    "name": "Általános szűrés",
    "description": "Éves rutinvizsgálat",
    "duration": 60,
    "price": 15000,
    "doctor_id": "698a3e705cf74c640c1f4b1c"
}

### 2.3 HIBÁS TESZT: Orvos próbál szolgáltatást létrehozni MÁS orvoshoz
# 403 Forbidden-t kell kapnod
POST {{baseUrl}}/services
Authorization: Bearer {{doctorLogin.response.body.token}}
Content-Type: application/json

{
    "name": "Hackelési kísérlet",
    "doctor_id": "698c3994ee508c5a604e1987"
}