@baseUrl = http://localhost:3000/api
###VERCEL
###@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 1.1 Összes felhasználó lekérése ADMIN ONLY
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OWZmNzZhMGI4YjJiNTUzYzQwMDM2OSIsImlhdCI6MTc3MjEwODI1MCwiZXhwIjoxNzc0NzAwMjUwfQ.raMXwFgP60aqs8sBFxz7V8AjRcrm-rwvCHHu9B32OX8
### 1.2 Összes orvos lekérése
GET {{baseUrl}}/users/doctors
Content-Type: application/json

### 1.3 Összes páciens lekérése ADMIN/DOCTOR ONLY
GET {{baseUrl}}/users/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTRhZmZkMWViYTFhNzFhYTY4YjNlOCIsImlhdCI6MTc3MTQ5MTc0OSwiZXhwIjoxNzc0MDgzNzQ5fQ.xE9bAJWe7o3-FWAA52yrg6t3FHMiiAYWro2hLehwDH8
Content-Type: application/json

### 2. Regisztráció 
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Kapocsi Hunor László",
    "email": "suekebenedek2@gmail.com",
    "password": "doktorcigany2",
    "phone": "+36709998877",
    "address": "9024, Győr, Nádor utca 11",
    "specialization": "Végbéltan",
    "birthDate": "1990-01-01",
    "tajNumber": "666666666",
    "role": "PATIENT"
}
 

### 3. Bejelentkezés
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "doktor@gmail.com",
    "password": "doktorcigany2"
}
###
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "doktor@gmail.com",
    "password": "doktorcigany2"
}
### 4. Profil lekérése
GET {{baseUrl}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljMjZmNDcyNzgyMTdlNjY3NjgyNCIsImlhdCI6MTc3MDcxNzk5NSwiZXhwIjoxNzczMzA5OTk1fQ.ZXSpY_mIvvzw-eDjwke76xvNHw5oknhm0ynEALcqDjU

### 5. Profil frissítése
PUT {{baseUrl}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTJjNDQzNmUzZTIyMmRhZWIxYjMzNSIsImlhdCI6MTc3MTIyNzA4NiwiZXhwIjoxNzczODE5MDg2fQ.UKkHN57erg_VU9pKmTVPjZok4thsZcXFT3edO_2Zy-E
Content-Type: application/json

{
    "address": "9142, Rábapatona, Pusztulat u.6666"
}

###6. Kijelentkezés (Token törlése a kliens oldalon, itt csak szimbolikus)
POST {{baseUrl}}/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljMjZmNDcyNzgyMTdlNjY3NjgyNCIsImlhdCI6MTc3MDY2Nzc3MSwiZXhwIjoxNzczMjU5NzcxfQ.14GEamK8aUT1Qcl-8971DKlMmEEKYuvh91eXatLiRpM
### 7. Felhasználó törlése ID alapján (Admin vagy Saját maga)
DELETE {{baseUrl}}/users/698f4331ea9679d8780c6241
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGVlNWQxODQzNjA1Mjk5MTgyNWIxYyIsImlhdCI6MTc3MDk5NTU3MywiZXhwIjoxNzczNTg3NTczfQ.eouIIS11fw7N03qoW_0pnV9oylE4Wr8xx-SddYItpjQ

