@baseUrl = http://localhost:3000/api
###VERCEL
###@baseUrl = https://romandi-vadaszhaz-klinik-backend.vercel.app/api

### 1.1 Összes felhasználó lekérése ADMIN ONLY
GET {{baseUrl}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGVlNWQxODQzNjA1Mjk5MTgyNWIxYyIsImlhdCI6MTc3MDk3Mjg0NywiZXhwIjoxNzczNTY0ODQ3fQ.jkGye_KOwrTBc-N5srVy8L0nXx5nfcGOLyZChKaoOkY
Content-Type: application/json
### 1.2 Összes orvos lekérése
GET {{baseUrl}}/users/doctors
Content-Type: application/json

### 1.3 Összes páciens lekérése ADMIN/DOCTOR ONLY
GET {{baseUrl}}/users/patients
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGEzZTcwNWNmNzRjNjQwYzFmNGIxYyIsImlhdCI6MTc3MDY2ODk4MCwiZXhwIjoxNzczMjYwOTgwfQ.6D_iQuX_dpyPz8QRi7XtfdkmTdf26eSWAwr4HzuWqp4
Content-Type: application/json

### 2. Regisztráció 
POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Csöngető Csongot",
    "email": "csongeto.csongor@students.jedlik.eu",
    "password": "doktorcigany2",
    "phone": "+36709998877",
    "address": "9142, Rábapatona, Dózsa utca 56/B",
    "specialization": "Végbéltan",
    "birthDate": "1990-01-01",
    "tajNumber": "666666666",
    "role": "DOCTOR"
}
 

### 3. Bejelentkezés
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "doktorcigany2"
}
###
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "pinter.balint@students.jedlik.eu",
    "password": "doktorcigany2"
}
### 4. Profil lekérése
GET {{baseUrl}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljMjZmNDcyNzgyMTdlNjY3NjgyNCIsImlhdCI6MTc3MDcxNzk5NSwiZXhwIjoxNzczMzA5OTk1fQ.ZXSpY_mIvvzw-eDjwke76xvNHw5oknhm0ynEALcqDjU

### 5. Profil frissítése
PUT {{baseUrl}}/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGY0MjQxZWE5Njc5ZDg3ODBjNjIzNSIsImlhdCI6MTc3MDk5NzcxMCwiZXhwIjoxNzczNTg5NzEwfQ.ByN-cp8wGQPAgob7x6BJMbaS9GumloIHOd0llU5ibaA
Content-Type: application/json

{
    "name": "Pintér Bálint",
    "address": "Csöves"
}

###6. Kijelentkezés (Token törlése a kliens oldalon, itt csak szimbolikus)
POST {{baseUrl}}/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODljMjZmNDcyNzgyMTdlNjY3NjgyNCIsImlhdCI6MTc3MDY2Nzc3MSwiZXhwIjoxNzczMjU5NzcxfQ.14GEamK8aUT1Qcl-8971DKlMmEEKYuvh91eXatLiRpM
### 7. Felhasználó törlése ID alapján (Admin vagy Saját maga)
DELETE {{baseUrl}}/users/698f4331ea9679d8780c6241
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OGVlNWQxODQzNjA1Mjk5MTgyNWIxYyIsImlhdCI6MTc3MDk5NTU3MywiZXhwIjoxNzczNTg3NTczfQ.eouIIS11fw7N03qoW_0pnV9oylE4Wr8xx-SddYItpjQ